---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/tunupublsh/repositories/MESHTECH-V2.6
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && npm install --omit=dev --legacy-peer-deps
